### ISSUE TITLE
how to create blastdb

### ISSUE THREAD

**Issue by jamesonypy** [urmi-21/PLncPRO#1]
i am trying to build the model and predict , but i don't know the steps , i have the protein data and mRNA, how to create blastdb?

**Comment by urmi-21** [comment]
Hi @jamesonypy, plncpro works with transcript sequences (mRNA). Full instructions to create blastdb are [here](https://github.com/urmi-21/PLncPRO/blob/master/examples/Build%20and%20test%20monocot%20model.ipynb)

You may also use Diamond instead of blast (diamond is much faster). See the [README](https://github.com/urmi-21/PLncPRO/blob/master/README.md) for instructions on how to use diamond instead of blast.
